#AI Assisted Code
#Generated by Claude
#Adapted by Authors

import hashlib
import json
import time
from pathlib import Path

import pandas as pd
import requests

Y0, Y1 = 2015, 2024

POINTS = [
    ("Sevilla", 37.39, -5.99),
    ("CReal",   38.98, -3.93),
    ("Duero",   41.50, -5.75),
    ("Ebro",    42.47,  0.75),
]

TECHS = ["Solar", "Hydro Run-of-River", "Hydro water reservoir"]
WX_VARS = ["temperature_2m_max", "temperature_2m_mean",
           "shortwave_radiation_sum", "precipitation_sum"]

CACHE, OUT = Path("cache"), Path("data/Q1_Data")


def get(url, params, tag, sleep=8.0):
    CACHE.mkdir(exist_ok=True)
    key = hashlib.md5(f"{url}{sorted(params.items())}".encode()).hexdigest()[:10]
    f = CACHE / f"{tag}_{key}.json"
    if f.exists():
        return json.loads(f.read_text())
    for attempt in range(1, 13):
        r = requests.get(url, params=params, timeout=180)
        if r.status_code == 429:
            wait = max(60.0, min(60.0 * attempt, 900.0))
            print(f"  Rate Limit bei {tag} - warte {wait:.0f}s")
            time.sleep(wait)
            continue
        r.raise_for_status()
        f.write_text(json.dumps(r.json()))
        time.sleep(sleep)
        return r.json()
    raise RuntimeError(f"Rate Limit bei {tag} haelt an. Spaeter neu starten.")

frames = []
for y in range(Y0, Y1 + 1):
    print(f"Erzeugung {y}")
    p = get("https://api.energy-charts.info/public_power",
            {"country": "es", "start": f"{y}-01-01", "end": f"{y}-12-31"},
            f"power_{y}")
    frames.append(pd.DataFrame(
        {t["name"]: t["data"] for t in p["production_types"]},
        index=pd.to_datetime(p["unix_seconds"], unit="s", utc=True)))

gen = pd.concat(frames).sort_index()
gen = gen[~gen.index.duplicated(keep="first")]
gen.index.name = "timestamp_utc"

frames = []
for name, lat, lon in POINTS:
    print(f"Wetter {name}")
    p = get("https://archive-api.open-meteo.com/v1/archive",
            {"latitude": lat, "longitude": lon,
             "start_date": f"{Y0}-01-01", "end_date": f"{Y1}-12-31",
             "daily": ",".join(WX_VARS), "timezone": "UTC"},
            f"wx_main_{name}", sleep=10.0)
    block = p[0] if isinstance(p, list) else p
    d = pd.DataFrame(block["daily"])
    d["date"] = pd.to_datetime(d.pop("time"))
    frames.append(d.set_index("date"))

wx = sum(frames) / len(frames)
wx.index.name = "date"

step = pd.Series(gen.index).diff().dt.total_seconds().div(3600).bfill().to_numpy()

res = pd.Series(step, index=gen.index).groupby(gen.index.year).agg(
    lambda s: ", ".join(f"{v:g}h" for v in sorted(s.unique())))
print("\nZeitaufloesung je Jahr:")
for y, v in res.items():
    print(f"  {y}: {v}")

g = gen[TECHS].mul(step, axis=0)
g.index = g.index.tz_convert("Europe/Madrid")
daily = g.groupby(g.index.date).sum()
daily.index = pd.to_datetime(daily.index)
daily.index.name = "date"

panel = daily.join(wx, how="inner")

OUT.mkdir(parents=True, exist_ok=True)
panel.to_csv(OUT / "panel_daily.csv")

print(f"\n{len(panel)} Tage, {panel.index.min().date()} bis {panel.index.max().date()}")
print(f"CSV-Datei in {OUT.resolve()}")
